config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do

  end
  resources :comments
  resources :tags
  resources :users
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commmentable, polymorphic: true
  belongs_to :user
  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags

  validates :title, presence: true
  validates :content, presence: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable, except: [:destroy, :edit]

  def new
    @commment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_to  "/#{params[:comment][:commentable_type]}/#{@commentable.id}", notice: 'Comment saved!'
    else
      redirect_to root_path, alert: "Didn't save comment"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    if @comment.commentable_type == 'User'
      @user = User.find(@comment.commentable_id)
    else
      @post = Post.find(@comment.commentable_id)
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to  "/#{params[:comment][:commentable_type]}/#{@commentable.id}", notice: 'Comment saved!'
    else
      redirect_to root_path, alert: "Didn't save comment"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    resource = @comment.commentable_type.pluralize.downcase
    id = @comment.commentable_id
    @comment.destroy
    redirect_to "/#{resource}/#{id}", alert: 'Comment deleted!'
  end
  private
  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end

  def load_commentable
    @commentable = params[:comment][:commentable_type].singularize.classify.constantize.find(params[:comment][:commentable_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]
  before_action :find_tags, only: [:index, :new, :edit, :create]

  def index
    @posts = Post.all.order( 'created_at desc')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:tags]
      params[:tags].each do |tag|
        @post.tags << Tag.find_by_name(tag)
      end
    end

    if @post.save
      redirect_to posts_path, notice: "Post created!"
    else
      render :new, alert: 'Post not saved!'
    end
  end

  def show
    @comment = Comment.new
  end

  def edit

  end


  def update
    if params[:tags]
      params[:tags].each do |tag|
        @post.tags << Tag.find_by_name(tag)
      end
    else
      @post.tags.each do |tag|
        @post.tags.delete(tag)
      end
    end

    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private

  def tag_params
    params.require(:tags).permit(:name)
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_tags
    @tags = Tag.all
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, except: [:new, :create, :index]


  def index
    @tags = @post.tags
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @tag.destroy
    redirect_to posts_path
  end


  private
  def find_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:new, :index, :create]

  def index
    @users = User.all
  end

  def show
    @comment = Comment.new  
  end

  private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<% if @comment.commentable_type == 'User' %>
  <%= render 'users/comment_form' %>
<% else %>
  <%= render 'posts/comment_form' %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogAgain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Blog Again', posts_path, class: 'navbar-brand' %>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', posts_path %></li>
          <% if current_user %>
            <li><%= link_to 'Create Post', new_post_path %></li>
            <li><%= link_to 'Create Tag', new_tag_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Posts', posts_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% unless current_user %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% else %>
            <li><a><%= current_user.user_name %></a></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
<div class='container'>
  <% if alert %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>

  <% if notice %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
  <br>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :commentable_id, value: @post.id %>
  <%= f.hidden_field :commentable_type, value: "posts" %>
  <%= f.text_field :content, class: 'form-control', placeholder: 'Enter comment here' %>
  <br>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', object: @post %>
<%= form_for @post do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', cols: 20, rows: 20 %>
  </div>
  <div class='form-control'>
    <% @tags.each do |t| %>
    <%= label_tag t.name  %>
    <%= check_box_tag "tags[#{t.name}]", t.name  %>
    <% end %>
  </div>
  <br>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/posts/index.html.erb
<div class='jumbotron row'>
  <center><h1>Blog Again</h1></center>
</div>


<div class='row well'>
  <h3>Tags:</h3><% @tags.each do |tag| %>
    <div class='col-sm-3'>
      <h4><%= link_to tag.name, tag_path(tag) %></h4>
    </div>
  <% end %>
</div>

<% if current_user %>
  <center><%= link_to 'Add Post', new_post_path, class: 'btn btn-primary btn-lg' %></center>
<% else %>
  <center><%= link_to 'Add Post', new_user_session_path, class: 'btn btn-primary btn-lg' %></center>
<% end %>
<div class='row'>
  <% @posts.each do |post| %>
      <div class='col-md-12'>
        <h3><%= link_to post.title, post_path(post) %> <small>created <%= time_ago_in_words post.created_at %> ago</small></h3>
      </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class='row well'>
  <h3>Tags:</h3><% @post.tags.each do |tag| %>
    <div class='col-sm-4'>
      <h4><%= link_to tag.name, tag_path(tag) %></h4>
    </div>
  <% end %>
</div>


<div class="panel panel-default row">
  <div class="panel-heading"><h1><%= @post.title %></h1></div>
  <div class="panel-body">
    <p class='post-content'>
      <%= @post.content %>
    </p>
  </div>
</div>

<% if current_user %>
  <%= link_to 'Edit', edit_post_path(@post) %>
  <%= link_to 'Delete', post_path(@post), data: { confirm: 'Are you sure?', method: 'delete' } %>
<% end %>

<div id="content"></div>

<h4>Comments</h4>
<% if current_user %>
  <%= render 'comment_form' %>
<% end %>
<br>
<ul>
  <% @post.comments.order( 'created_at desc').each do |comment| %>
    <li><span class='comment-author'><%= comment.user.user_name %></span>:
      <span class='comment'><%= comment.content %></span>
      <small>commented <%= time_ago_in_words comment.created_at %> ago</small>
      <%= link_to 'edit', edit_comment_path(comment) if current_user.id == comment.user.id %>
      <%= link_to 'delete', comment_path(comment), data: { confirm: 'Are you sure?', method: 'delete' } if current_user.id == comment.user.id %></li>
  <% end %>
</ul>

app/views/tags/_form.html.erb
<%= render 'layouts/errors', object: @tag %>
<%= form_for [@tag] do |f| %>
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/tags/edit.html.erb
<%= render 'form' %>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% if current_user %>
  <%= link_to 'Edit', edit_tag_path(@tag) %>
  <%= link_to 'Delete', tag_path, data: { confirm: 'Are you sure?', method: 'delete' } %>
<% end %>

<div class='row well'>
  <h3>Posts:</h3><% @tag.posts.each do |post| %>
    <div class='col-sm-12'>
      <h4><%= link_to post.title, post_path(post) %></h4>
    </div>
  <% end %>
</div>

app/views/users/_comment_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :commentable_id, value: @user.id %>
  <%= f.hidden_field :commentable_type, value: "users" %>
  <%= f.text_field :content, class: 'form-control', placeholder: 'Enter comment here' %>
  <br>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |u| %>
    <li class='comment-author'><%= link_to u.user_name, user_path(u) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.user_name %></h1>

<h4>Comments</h4>
<% if current_user %>
  <%= render 'comment_form' %>
<% end %>
<br>
<ul>
  <% Comment.where("commentable_type = ? AND commentable_id = ?", "User", @user.id).order( 'created_at desc').each do |comment| %>
  <li><span class='comment-author'><%= comment.user.user_name %></span>:
    <span class='comment'><%= comment.content %></span> <small>commented <%= time_ago_in_words comment.created_at %> ago</small>
    <%= link_to 'edit', edit_comment_path(comment) if current_user.id == comment.user.id %>
    <%= link_to 'delete', comment_path(comment), data: { confirm: 'Are you sure?', method: 'delete' } if current_user.id == comment.user.id %> </li>
  <% end %>
</ul>